/**
 * Seed script — replaces ALL existing products with real Nandini KMF products.
 * Uses official KMF product images from their S3 bucket.
 *
 * Usage:  node src/scripts/seedNandiniProducts.js
 */

import mongoose from "mongoose"
import dotenv from "dotenv"
dotenv.config()

const MONGO_URI =
  process.env.MONGO_URI ||
  "mongodb+srv://aiwats748:vSGV3vcPmrb4rOZ1@cluster0.swjkv.mongodb.net/aiwats"

const variantSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    sku: String,
    sellingPrice: { type: Number, required: true },
    shopPrice: { type: Number, required: true },
    b2bPrice: Number,
    stock: { type: Number, default: 0 },
    minB2BQty: { type: Number, default: 1 },
  },
  { _id: true },
)

const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    category: String,
    subcategory: String,
    description: String,
    details: String,
    isVeg: { type: Boolean, default: true },
    rating: { type: Number, default: 4.5 },
    unit: String,
    shopPrice: { type: Number, required: true },
    marginPercent: { type: Number, default: 20 },
    sellingPrice: { type: Number, required: true },
    image: String,
    inStock: { type: Boolean, default: true },
    variants: [variantSchema],
    shelfLife: Number,
    storageTemp: String,
    isSubscribable: { type: Boolean, default: false },
    tags: [String],
    shopIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "Shop" }],
    sponsor: {
      shopId: { type: mongoose.Schema.Types.ObjectId, ref: "Shop" },
      shopName: String,
      discountPercent: Number,
      area: String,
    },
  },
  { timestamps: true },
)

const Product =
  mongoose.models.Product || mongoose.model("Product", productSchema)

// ══════════════════════════════════════════════════════════════════════
// REAL NANDINI KMF PRODUCT CATALOG — with official images
// ══════════════════════════════════════════════════════════════════════

const products = [
  // ─── MILK ──────────────────────────────────────────────────────────
  {
    name: "Nandini Pasteurised Toned Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Nandini pasteurised toned milk, fresh daily from Karnataka farms",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/m1_6e1cb0de1f.png",
  },
  {
    name: "Nandini Double Toned Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 20,
    sellingPrice: 23,
    description: "Low-fat double toned milk for health-conscious consumers",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/m2_c8279880b0.jpg",
  },
  {
    name: "Nandini Homogenised Cow's Pure Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 26,
    sellingPrice: 30,
    description: "Pure homogenised cow milk with natural goodness",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/HCM_500_ml_BAMUL_front_9b2b553c71.png",
  },
  {
    name: "Nandini Samrudhi Full Cream Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 28,
    sellingPrice: 32,
    description: "Rich full cream pasteurized Samrudhi milk",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    tags: ["bestseller"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Samrudhi_500_ml_Front_55b767ea9b.png",
  },
  {
    name: "Nandini Special Toned Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 18,
    sellingPrice: 21,
    description: "Economical special toned milk",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/m5_7d02e1654b.png",
  },
  {
    name: "Nandini Shubham Gold Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 30,
    sellingPrice: 35,
    description: "Premium Shubham gold standardised milk",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    tags: ["new"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/m6_e913e98ba3.png",
  },
  {
    name: "Nandini Desi Cow Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 32,
    sellingPrice: 38,
    description: "Pure desi cow milk from indigenous breeds",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    tags: ["new"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/m7_0bd988a567.png",
  },
  {
    name: "Nandini Homogenised Toned Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 24,
    sellingPrice: 27,
    description: "Homogenised toned milk for everyday use",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/HTM_500_ml_BIMUL_1_d2553c4d12.png",
  },
  {
    name: "Nandini Standardised Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 24,
    sellingPrice: 28,
    description: "Shubham pasteurised homogenised standardised milk",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/HSTD_500_ml_BIMUL_1_60fbc0d70c.png",
  },
  {
    name: "Nandini Buffalo Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 30,
    sellingPrice: 35,
    description: "Rich and creamy buffalo milk",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Nandini_Buffalo_Milk_500ml_Front_2_3e4337f32a.png",
  },
  {
    name: "Nandini Santhrupthi Milk",
    category: "MILK",
    unit: "500 ml",
    shopPrice: 22,
    sellingPrice: 26,
    description: "Nandini Santhrupthi milk for daily needs",
    storageTemp: "2-8°C",
    shelfLife: 2,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Santhrupthi_500_01_51cd65c48b.png",
  },
  {
    name: "Nandini N-PRO Milk",
    category: "MILK",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Protein enriched N-PRO milk",
    storageTemp: "2-8°C",
    shelfLife: 5,
    tags: ["new"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_ebe2d4a1b9.jpg",
  },

  // ─── CURD ──────────────────────────────────────────────────────────
  {
    name: "Nandini Curd",
    category: "CURD",
    unit: "500 ml",
    shopPrice: 28,
    sellingPrice: 32,
    description: "Fresh set curd, naturally fermented daily",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Curd_Kannada_05_5383d02e7e.png",
  },
  {
    name: "Nandini 5 KG Bucket Curd",
    category: "CURD",
    unit: "5 kg",
    shopPrice: 220,
    sellingPrice: 260,
    description: "Large bucket curd for families and events",
    storageTemp: "2-8°C",
    shelfLife: 5,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_3629516fd4.png",
  },
  {
    name: "Nandini 10 KG Bucket Curd",
    category: "CURD",
    unit: "10 kg",
    shopPrice: 420,
    sellingPrice: 490,
    description: "Bulk bucket curd for commercial use",
    storageTemp: "2-8°C",
    shelfLife: 5,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Cap_Curd_10kg_1_2ec2847379.png",
  },
  {
    name: "Nandini Probiotic Curd",
    category: "CURD",
    unit: "400 g",
    shopPrice: 38,
    sellingPrice: 45,
    description: "Probiotic curd with live active cultures for gut health",
    storageTemp: "2-8°C",
    shelfLife: 7,
    tags: ["new"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Probiotic_Curd_Front_85934fcf1f.png",
  },
  {
    name: "Nandini Set Curd",
    category: "CURD",
    unit: "400 g",
    shopPrice: 32,
    sellingPrice: 38,
    description: "Thick and creamy set curd",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Set_Curd_1_400g_19c086c000.png",
  },
  {
    name: "Nandini Curd Lite",
    category: "CURD",
    unit: "500 g",
    shopPrice: 30,
    sellingPrice: 35,
    description: "Low-fat lite curd for health conscious",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Nandini_Curd_Lite_500g_Front_c5a8ffe7ea.png",
  },
  {
    name: "Nandini Premium Curd",
    category: "CURD",
    unit: "400 g",
    shopPrice: 35,
    sellingPrice: 42,
    description: "Premium quality thick curd",
    storageTemp: "2-8°C",
    shelfLife: 5,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/IMG_20241109_WA_0007_787069d08e.jpg",
  },

  // ─── GHEE ──────────────────────────────────────────────────────────
  {
    name: "Nandini Ghee 500ml",
    category: "GHEE",
    unit: "500 ml",
    shopPrice: 260,
    sellingPrice: 295,
    description: "Pure cow ghee with rich aroma, 500ml jar",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["bestseller"],
    rating: 4.9,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/ghee_500_1_48c0d0846a.png",
  },
  {
    name: "Nandini Ghee 200ml",
    category: "GHEE",
    unit: "200 ml",
    shopPrice: 110,
    sellingPrice: 125,
    description: "Pure cow ghee sachet, convenient 200ml pack",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/ghee_200_1_844c0a172d.png",
  },
  {
    name: "Nandini Ghee 1 Litre",
    category: "GHEE",
    unit: "1 L",
    shopPrice: 500,
    sellingPrice: 560,
    description: "Premium quality ghee, 1 litre jar",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["bestseller"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/ghee_1000_1_ee0121d4c4.png",
  },
  {
    name: "Nandini Ghee 5 Litre",
    category: "GHEE",
    unit: "5 L",
    shopPrice: 2400,
    sellingPrice: 2700,
    description: "Bulk 5 litre pet jar ghee for families",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Ghee_Pet_Jar_5_Litre_Mockup_439888ea58.png",
  },
  {
    name: "Nandini Ghee 15 KG",
    category: "GHEE",
    unit: "15 kg",
    shopPrice: 7200,
    sellingPrice: 8100,
    description: "Commercial pack ghee, 15kg tin",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/15kg_1_398470aabc.png",
  },
  {
    name: "Nandini Ghee Sachets",
    category: "GHEE",
    unit: "100 ml",
    shopPrice: 55,
    sellingPrice: 65,
    description: "Convenient single-use ghee sachets",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/100ml_1_ac16fa6ac2.png",
  },
  {
    name: "Nandini Desi Cow Ghee Jar",
    category: "GHEE",
    unit: "500 ml",
    shopPrice: 320,
    sellingPrice: 370,
    description: "Premium desi cow ghee in glass jar",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["new"],
    rating: 4.9,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/500_1_780d4841e7.png",
  },
  {
    name: "Nandini Good Life Ghee",
    category: "GHEE",
    unit: "500 ml",
    shopPrice: 300,
    sellingPrice: 345,
    description: "Good Life range premium ghee",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["new"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_8047e5b7ef.png",
  },

  // ─── BUTTER ────────────────────────────────────────────────────────
  {
    name: "Nandini Salted Butter",
    category: "BUTTER",
    unit: "100 g",
    shopPrice: 45,
    sellingPrice: 52,
    description: "Lightly salted premium table butter",
    storageTemp: "2-8°C",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Nandini_Butter_Salted_100g_Front_render_7bca5b07e7.png",
  },
  {
    name: "Nandini Unsalted Butter",
    category: "BUTTER",
    unit: "200 g",
    shopPrice: 80,
    sellingPrice: 95,
    description: "Pure unsalted white butter for cooking",
    storageTemp: "2-8°C",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Nandini_Butter_Unsalted_200g_Front_render_ec8d3cd73b.png",
  },
  {
    name: "Nandini Butter Chiplets",
    category: "BUTTER",
    unit: "1 kg",
    shopPrice: 380,
    sellingPrice: 440,
    description: "Individual butter chiplet portions, bulk pack",
    storageTemp: "2-8°C",
    shelfLife: 60,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Nandini_Chiplet_Outer_Box_1_Kg_Render_1_92916a299f.png",
  },
  {
    name: "Nandini Good Life Buttery Spread",
    category: "BUTTER",
    unit: "200 g",
    shopPrice: 75,
    sellingPrice: 90,
    description: "Smooth and creamy buttery spread",
    storageTemp: "2-8°C",
    shelfLife: 60,
    tags: ["new"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Buttery_Spread_front_6071860c67.png",
  },

  // ─── PANEER ────────────────────────────────────────────────────────
  {
    name: "Nandini Fresh Paneer",
    category: "PANEER",
    unit: "200 g",
    shopPrice: 70,
    sellingPrice: 80,
    description: "Soft and fresh cottage cheese",
    storageTemp: "2-8°C",
    shelfLife: 7,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/200g_1c6b917051.png",
  },
  {
    name: "Nandini Fresh Paneer 500g",
    category: "PANEER",
    unit: "500 g",
    shopPrice: 165,
    sellingPrice: 190,
    description: "Fresh paneer, large family pack",
    storageTemp: "2-8°C",
    shelfLife: 7,
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/500g_7c120ccc61.png",
  },
  {
    name: "Nandini Frozen Paneer",
    category: "PANEER",
    unit: "200 g",
    shopPrice: 72,
    sellingPrice: 85,
    description: "Frozen paneer with longer shelf life",
    storageTemp: "-18°C",
    shelfLife: 30,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/200g_9954be392c.png",
  },
  {
    name: "Nandini Medium Fat Paneer",
    category: "PANEER",
    unit: "200 g",
    shopPrice: 65,
    sellingPrice: 75,
    description: "Medium fat paneer for health-conscious cooking",
    storageTemp: "2-8°C",
    shelfLife: 7,
    tags: ["new"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_0cbbb5f9e0.png",
  },
  {
    name: "Nandini Buffalo Paneer",
    category: "PANEER",
    unit: "200 g",
    shopPrice: 75,
    sellingPrice: 88,
    description: "Rich buffalo milk paneer",
    storageTemp: "2-8°C",
    shelfLife: 7,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Buffalo_Panner_Pkg_Mockup_1_front_51a7cc87b9.png",
  },

  // ─── CHEESE ────────────────────────────────────────────────────────
  {
    name: "Nandini Processed Cheese Block",
    category: "CHEESE",
    unit: "200 g",
    shopPrice: 85,
    sellingPrice: 99,
    description: "Smooth processed cheese block",
    storageTemp: "2-8°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_f45b7bfc29.png",
  },
  {
    name: "Nandini Cheddar Cheese",
    category: "CHEESE",
    unit: "200 g",
    shopPrice: 110,
    sellingPrice: 130,
    description: "Aged cheddar cheese with rich flavor",
    storageTemp: "2-8°C",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_96bf3c3e9c.png",
  },
  {
    name: "Nandini Processed Cheese Cubes",
    category: "CHEESE",
    unit: "200 g",
    shopPrice: 90,
    sellingPrice: 105,
    description: "Convenient cheese cubes for snacking",
    storageTemp: "2-8°C",
    shelfLife: 90,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_cac45780b3.png",
  },
  {
    name: "Nandini Cheese Slices",
    category: "CHEESE",
    unit: "200 g",
    shopPrice: 95,
    sellingPrice: 110,
    description: "Individually wrapped cheese slices",
    storageTemp: "2-8°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Front_Angle_Image_d73201f046.png",
  },

  // ─── FLAVORED MILK ─────────────────────────────────────────────────
  {
    name: "Nandini Badam Flavored Milk",
    category: "FLAVORED MILK",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Rich badam flavored milk drink",
    storageTemp: "2-8°C",
    shelfLife: 7,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Badam_jpg_cdf02419f1.jpeg",
  },
  {
    name: "Nandini Pista Flavored Milk",
    category: "FLAVORED MILK",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Refreshing pista flavored milk",
    storageTemp: "2-8°C",
    shelfLife: 7,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/pista_jpg_d8636026ac.jpeg",
  },
  {
    name: "Nandini Elaichi Flavored Milk",
    category: "FLAVORED MILK",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Aromatic elaichi flavored milk",
    storageTemp: "2-8°C",
    shelfLife: 7,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Elaichi_jpg_43b288f12f.jpeg",
  },
  {
    name: "Nandini Rose Flavored Milk",
    category: "FLAVORED MILK",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Sweet rose flavored milk",
    storageTemp: "2-8°C",
    shelfLife: 7,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/DSC_02128_30104ca7dc.JPG",
  },
  {
    name: "Nandini Litchi Flavored Milk",
    category: "FLAVORED MILK",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 25,
    description: "Fruity litchi flavored milk",
    storageTemp: "2-8°C",
    shelfLife: 7,
    tags: ["new"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Litchi_jpg_f5ca607667.jpeg",
  },

  // ─── FLAVORED MILK IN TETRA ────────────────────────────────────────
  {
    name: "Nandini Badam Tetra Pack",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Long-life badam milk in tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/badam_4529b90b9d.png",
  },
  {
    name: "Nandini Pista Tetra Pack",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Pista flavored milk in tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/pista_b161046220.png",
  },
  {
    name: "Nandini Strawberry Tetra Pack",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Strawberry flavored milk tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/strawberry_121df20184.png",
  },
  {
    name: "Nandini Mango Milkshake Tetra",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Mango milkshake in tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/MILK_SHAKE_TETRA_MANGO_695d892215.png",
  },
  {
    name: "Nandini Butterscotch Milkshake Tetra",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Butterscotch milkshake in tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/MILK_SHAKE_TETRA_BUTTER_SCOTCH_77038abb0b.png",
  },
  {
    name: "Nandini Lassi Tetra Pack",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 20,
    sellingPrice: 25,
    description: "Sweet lassi in convenient tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/LASSI_TETRA_SWEET_96afdf3344.png",
  },
  {
    name: "Nandini Buttermilk Tetra Pack",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 15,
    sellingPrice: 20,
    description: "Spiced buttermilk in tetra pack",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/buttermilk_96f79bf1b1.png",
  },
  {
    name: "Nandini Mango Splash",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Refreshing mango splash drink",
    storageTemp: "Room temp",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/SPLASH_TETRA_MANGO_4c66aef7a6.png",
  },
  {
    name: "Nandini Orange Splash",
    category: "FLAVORED MILK IN TETRA",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Tangy orange splash drink",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.3,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/SPLASH_TETRA_ORANGE_8a477beb61.png",
  },

  // ─── CHOCOLATES ────────────────────────────────────────────────────
  {
    name: "Nandini Energy Bar Caramel",
    category: "CHOCOLATES",
    unit: "22 g",
    shopPrice: 8,
    sellingPrice: 10,
    description: "Delicious caramel energy bar",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/12_Rich_Bar_Delicious_Caramel_22g_1_4b6e193bb3.png",
  },
  {
    name: "Nandini Energy Bar Wholesome Nuts",
    category: "CHOCOLATES",
    unit: "22 g",
    shopPrice: 8,
    sellingPrice: 10,
    description: "Crunchy wholesome nuts energy bar",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/10_Energy_Bar_Wholesome_Nuts_22g_1_c14b84e9da.png",
  },
  {
    name: "Nandini Energy Bar Zesty Fruits",
    category: "CHOCOLATES",
    unit: "22 g",
    shopPrice: 8,
    sellingPrice: 10,
    description: "Zesty fruits energy bar",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/11_Energy_Bar_Zesty_Friuts_22g_1_dcd843478f.png",
  },
  {
    name: "Nandini Energy Delights Tin",
    category: "CHOCOLATES",
    unit: "1 tin",
    shopPrice: 180,
    sellingPrice: 220,
    description: "Premium energy delights assorted tin box",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["new"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Energy_Delights_Tin_Front_a1a1562543.png",
  },
  {
    name: "Nandini Almond Milk Choco",
    category: "CHOCOLATES",
    unit: "40 g",
    shopPrice: 25,
    sellingPrice: 30,
    description: "Almond milk chocolate bar",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/8906153560601_front_92fb932a80.png",
  },
  {
    name: "Nandini Delish Milk Choco",
    category: "CHOCOLATES",
    unit: "40 g",
    shopPrice: 22,
    sellingPrice: 28,
    description: "Delish smooth milk chocolate",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/8906036676443_front_39fbdfb63c.png",
  },
  {
    name: "Nandini Rice Crispies Milk Choco",
    category: "CHOCOLATES",
    unit: "80 g",
    shopPrice: 45,
    sellingPrice: 55,
    description: "Crunchy rice crispies milk chocolate",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/07_Rice_Crispies_80g_1_e91c2ef28d.png",
  },
  {
    name: "Nandini Rich Milk Chocolate",
    category: "CHOCOLATES",
    unit: "80 g",
    shopPrice: 45,
    sellingPrice: 55,
    description: "Rich creamy milk chocolate bar",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/08_Rich_Milk_80g_1_b0f9d4f7e7.png",
  },
  {
    name: "Nandini Utsava Gift Box",
    category: "CHOCOLATES",
    unit: "1 box",
    shopPrice: 250,
    sellingPrice: 299,
    description: "Premium festive chocolate gift box",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["new"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Final_Mock_Up_Blue_6aa413356f.png",
  },

  // ─── COOKIES ───────────────────────────────────────────────────────
  {
    name: "Nandini Butter Cookies",
    category: "COOKIES",
    unit: "100 g",
    shopPrice: 35,
    sellingPrice: 42,
    description: "Crunchy butter cookies made with Nandini butter",
    storageTemp: "Room temp",
    shelfLife: 120,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Butter_Cookies_1kg_1_36802729ed.png",
  },
  {
    name: "Nandini Choco Cookies",
    category: "COOKIES",
    unit: "100 g",
    shopPrice: 38,
    sellingPrice: 45,
    description: "Rich chocolate chip cookies",
    storageTemp: "Room temp",
    shelfLife: 120,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Choco_Cookies_Front_Perspective_ec6e783c70.png",
  },
  {
    name: "Nandini Coconut Cookies",
    category: "COOKIES",
    unit: "100 g",
    shopPrice: 35,
    sellingPrice: 42,
    description: "Coconut flavored crispy cookies",
    storageTemp: "Room temp",
    shelfLife: 120,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Cookies_Co_Co_Pkg_7d415cd67e.png",
  },
  {
    name: "Nandini Sweet & Salt Cookies",
    category: "COOKIES",
    unit: "100 g",
    shopPrice: 32,
    sellingPrice: 40,
    description: "Unique sweet and salt cookies blend",
    storageTemp: "Room temp",
    shelfLife: 120,
    tags: ["new"],
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Cookies_Sn_S_Pkg_3bf63f5800.png",
  },

  // ─── BAKED ─────────────────────────────────────────────────────────
  {
    name: "Nandini Milk Bread",
    category: "BAKED",
    unit: "400 g",
    shopPrice: 30,
    sellingPrice: 38,
    description: "Soft milk bread loaf",
    storageTemp: "Room temp",
    shelfLife: 3,
    tags: ["bestseller"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Milk_Bread_400g_1_Product_0bd2ba5946.jpg",
  },
  {
    name: "Nandini Multigrain Bread",
    category: "BAKED",
    unit: "400 g",
    shopPrice: 35,
    sellingPrice: 45,
    description: "Healthy multigrain bread",
    storageTemp: "Room temp",
    shelfLife: 3,
    tags: ["new"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Multi_Grain_Bread_400g_1_Product_4262878bd1.jpg",
  },
  {
    name: "Nandini Sandwich Bread",
    category: "BAKED",
    unit: "400 g",
    shopPrice: 32,
    sellingPrice: 40,
    description: "Perfect sandwich bread slices",
    storageTemp: "Room temp",
    shelfLife: 3,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Sandwich_Bread_400g_1_Product_f0b83b1882.jpg",
  },
  {
    name: "Nandini Wholewheat Bread",
    category: "BAKED",
    unit: "400 g",
    shopPrice: 35,
    sellingPrice: 42,
    description: "Wholesome wholewheat bread",
    storageTemp: "Room temp",
    shelfLife: 3,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Whole_Wheat_Bread_400g_1_Product_cfedb80d7e.jpg",
  },
  {
    name: "Nandini Vanilla Cream Bun",
    category: "BAKED",
    unit: "50 g",
    shopPrice: 12,
    sellingPrice: 15,
    description: "Soft bun with vanilla cream filling",
    storageTemp: "Room temp",
    shelfLife: 3,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/VANILLA_Cream_BUN_50g_1_Product_90cabfdd8e.jpg",
  },
  {
    name: "Nandini Chocolate Cream Bun",
    category: "BAKED",
    unit: "50 g",
    shopPrice: 12,
    sellingPrice: 15,
    description: "Soft bun with chocolate cream filling",
    storageTemp: "Room temp",
    shelfLife: 3,
    tags: ["bestseller"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Chocolate_CREAM_BUN_50g_1_Product_df1611928c.jpg",
  },
  {
    name: "Nandini Sweet Bun",
    category: "BAKED",
    unit: "250 g",
    shopPrice: 22,
    sellingPrice: 28,
    description: "Traditional sweet bun pack",
    storageTemp: "Room temp",
    shelfLife: 3,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Sweet_Bun_250gm_1_Product_337c27e35d.jpg",
  },
  {
    name: "Nandini Special Pav Bun",
    category: "BAKED",
    unit: "400 g",
    shopPrice: 25,
    sellingPrice: 32,
    description: "Special pav buns, soft and fresh",
    storageTemp: "Room temp",
    shelfLife: 3,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Special_Pav_Buns_400g_1_Product_6e898ccc8a.jpg",
  },
  {
    name: "Nandini Chocolate Cake",
    category: "BAKED",
    unit: "1 pc",
    shopPrice: 60,
    sellingPrice: 75,
    description: "Moist chocolate cake",
    storageTemp: "Room temp",
    shelfLife: 5,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/chocolate_cake_copy_bb7d94aeb0.jpg",
  },
  {
    name: "Nandini Fruit Cake",
    category: "BAKED",
    unit: "1 pc",
    shopPrice: 65,
    sellingPrice: 80,
    description: "Rich fruit cake with dry fruits",
    storageTemp: "Room temp",
    shelfLife: 7,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/fruit_cake_copy_e7942d1f27.jpg",
  },

  // ─── NAMKEENS ──────────────────────────────────────────────────────
  {
    name: "Nandini Benne Murukku",
    category: "NAMKEENS",
    unit: "200 g",
    shopPrice: 50,
    sellingPrice: 60,
    description: "Traditional Karnataka butter murukku",
    storageTemp: "Room temp",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Benne_Murukku_1_front_mock_png_d3fce0b51e.png",
  },
  {
    name: "Nandini Bombay Mixture",
    category: "NAMKEENS",
    unit: "200 g",
    shopPrice: 45,
    sellingPrice: 55,
    description: "Crunchy spicy Bombay mixture",
    storageTemp: "Room temp",
    shelfLife: 60,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Bombay_Mixture_1_front_mock_png_d96eb5a332.png",
  },
  {
    name: "Nandini Khara Boondi",
    category: "NAMKEENS",
    unit: "200 g",
    shopPrice: 42,
    sellingPrice: 52,
    description: "Spiced khara boondi snack",
    storageTemp: "Room temp",
    shelfLife: 60,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Khara_Boondi_1_front_mock_png_2e621b5da4.png",
  },
  {
    name: "Nandini Masala Kodubale",
    category: "NAMKEENS",
    unit: "200 g",
    shopPrice: 48,
    sellingPrice: 58,
    description: "Traditional masala kodubale",
    storageTemp: "Room temp",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Masala_Kodubale_1_front_mock_png_9c5b8c160a.png",
  },
  {
    name: "Nandini Paneer Murukku",
    category: "NAMKEENS",
    unit: "200 g",
    shopPrice: 50,
    sellingPrice: 60,
    description: "Paneer flavored crispy murukku",
    storageTemp: "Room temp",
    shelfLife: 60,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Panner_Murukku_1_front_mock_png_af33d43373.png",
  },

  // ─── INSTANT MIX ───────────────────────────────────────────────────
  {
    name: "Nandini Jamun Mix",
    category: "INSTANT MIX",
    unit: "200 g",
    shopPrice: 55,
    sellingPrice: 65,
    description: "Easy-to-make gulab jamun instant mix",
    storageTemp: "Room temp",
    shelfLife: 180,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/JAMOON_MIX_468adcb225.png",
  },
  {
    name: "Nandini Badam Milk Mix",
    category: "INSTANT MIX",
    unit: "200 g",
    shopPrice: 60,
    sellingPrice: 72,
    description: "Instant badam milk mix powder",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/badam_milk_mix_1_480d67e5f8.png",
  },
  {
    name: "Nandini Payasa Mix",
    category: "INSTANT MIX",
    unit: "200 g",
    shopPrice: 50,
    sellingPrice: 60,
    description: "Traditional payasa/kheer instant mix",
    storageTemp: "Room temp",
    shelfLife: 180,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Payasa_Mix_200g_1_1_a3606be15c.png",
  },

  // ─── NATURAL ICE-CREAM ─────────────────────────────────────────────
  {
    name: "Nandini Chikoo Natural Ice Cream",
    category: "NATURAL ICE-CREAM",
    unit: "750 ml",
    shopPrice: 150,
    sellingPrice: 180,
    description: "Natural chikoo flavored ice cream tub",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Chikoo_750_ml_1_1f0d6340ec.png",
  },
  {
    name: "Nandini Jack Fruit Ice Cream Tub",
    category: "NATURAL ICE-CREAM",
    unit: "750 ml",
    shopPrice: 160,
    sellingPrice: 195,
    description: "Unique jackfruit natural ice cream",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Jackfruit_750_ml_1_d08dbf9c8e.png",
  },
  {
    name: "Nandini Mango Ice Cream Tub",
    category: "NATURAL ICE-CREAM",
    unit: "750 ml",
    shopPrice: 155,
    sellingPrice: 190,
    description: "Natural Alphonso mango ice cream",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Mango_750_ml_1_5e32864cfe.png",
  },
  {
    name: "Nandini Pink Guava Ice Cream Tub",
    category: "NATURAL ICE-CREAM",
    unit: "750 ml",
    shopPrice: 150,
    sellingPrice: 185,
    description: "Pink guava natural ice cream",
    storageTemp: "-18°C",
    shelfLife: 90,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Pink_Guava_750_ml_1_0984fdda1b.png",
  },
  {
    name: "Nandini Tender Coconut Ice Cream Tub",
    category: "NATURAL ICE-CREAM",
    unit: "750 ml",
    shopPrice: 155,
    sellingPrice: 190,
    description: "Fresh tender coconut natural ice cream",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/Tender_Coconut_750_ml_1_947e978471.png",
  },

  // ─── CASSATA ───────────────────────────────────────────────────────
  {
    name: "Nandini Cassata Ice Cream",
    category: "CASSATA",
    unit: "750 ml",
    shopPrice: 140,
    sellingPrice: 170,
    description: "Classic tri-color cassata ice cream",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/18_casatta_fe0c45d8cb.png",
  },

  // ─── SUNDAE ────────────────────────────────────────────────────────
  {
    name: "Nandini Sundae Ice Cream",
    category: "SUNDAE",
    unit: "1 cup",
    shopPrice: 35,
    sellingPrice: 45,
    description: "Rich sundae ice cream cup with toppings",
    storageTemp: "-18°C",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/19_sundae_ab936101f6.png",
  },

  // ─── FAMILY PACK ICE-CREAM ─────────────────────────────────────────
  {
    name: "Nandini Family Pack Ice Cream",
    category: "FAMILY PACK ICE-CREAM",
    unit: "1 L",
    shopPrice: 150,
    sellingPrice: 180,
    description: "Family size ice cream tub, assorted flavors",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/20_family_pack_5d7ce73941.png",
  },

  // ─── CHOCO BAR ─────────────────────────────────────────────────────
  {
    name: "Nandini Choco Bar",
    category: "CHOCO BAR",
    unit: "1 pc",
    shopPrice: 18,
    sellingPrice: 25,
    description: "Chocolate coated ice cream bar",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/21_Chocobar_8175e18e2f.png",
  },

  // ─── ICE-CREAM ─────────────────────────────────────────────────────
  {
    name: "Nandini Ice Cream Assorted",
    category: "ICE-CREAM",
    unit: "500 ml",
    shopPrice: 95,
    sellingPrice: 115,
    description: "Assorted flavored ice cream tub",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/24_kulfi_882a18f74d.png",
  },

  // ─── CUP ICE-CREAMS ────────────────────────────────────────────────
  {
    name: "Nandini Cup Ice Cream",
    category: "CUP ICE-CREAMS",
    unit: "100 ml",
    shopPrice: 15,
    sellingPrice: 20,
    description: "Classic cup ice cream in various flavors",
    storageTemp: "-18°C",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/23_cup_ice_8376033333.png",
  },

  // ─── KULFI ICE-CREAM ───────────────────────────────────────────────
  {
    name: "Nandini Kulfi Ice Cream",
    category: "KULFI ICE-CREAM",
    unit: "1 pc",
    shopPrice: 20,
    sellingPrice: 25,
    description: "Traditional malai kulfi on stick",
    storageTemp: "-18°C",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/24_kulfi_882a18f74d.png",
  },

  // ─── GUDBUD ICE-CREAM ──────────────────────────────────────────────
  {
    name: "Nandini Gudbud Ice Cream",
    category: "GUDBUD ICE-CREAM",
    unit: "1 cup",
    shopPrice: 30,
    sellingPrice: 40,
    description: "Karnataka's famous Gudbud ice cream with dry fruits and jelly",
    storageTemp: "-18°C",
    shelfLife: 60,
    tags: ["bestseller"],
    rating: 4.9,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/25_gudbud_2fbf50216c.png",
  },

  // ─── SWEETS ────────────────────────────────────────────────────────
  {
    name: "Nandini Mysore Pak",
    category: "SWEETS",
    unit: "250 g",
    shopPrice: 100,
    sellingPrice: 120,
    description: "Traditional Mysore Pak made with Nandini ghee",
    storageTemp: "Room temp",
    shelfLife: 15,
    tags: ["bestseller"],
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/27_sweets_ef94802b19.png",
  },
  {
    name: "Nandini Peda",
    category: "SWEETS",
    unit: "250 g",
    shopPrice: 90,
    sellingPrice: 110,
    description: "Soft milk peda sweets",
    storageTemp: "Room temp",
    shelfLife: 10,
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/27_sweets_ef94802b19.png",
  },

  // ─── MILK POWDER ───────────────────────────────────────────────────
  {
    name: "Nandini Milk Powder",
    category: "MILK POWDER",
    unit: "500 g",
    shopPrice: 180,
    sellingPrice: 210,
    description: "Spray-dried whole milk powder",
    storageTemp: "Room temp",
    shelfLife: 365,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/28_Milk_powder_31f097fe3e.png",
  },
  {
    name: "Nandini Skimmed Milk Powder",
    category: "MILK POWDER",
    unit: "500 g",
    shopPrice: 160,
    sellingPrice: 190,
    description: "Low-fat skimmed milk powder",
    storageTemp: "Room temp",
    shelfLife: 365,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/28_Milk_powder_31f097fe3e.png",
  },

  // ─── NANDINI GOOD LIFE MILK ────────────────────────────────────────
  {
    name: "Nandini Good Life Toned Milk",
    category: "NANDINI GOOD LIFE MILK",
    unit: "500 ml",
    shopPrice: 26,
    sellingPrice: 30,
    description: "Premium toned milk from Good Life range",
    storageTemp: "2-8°C",
    shelfLife: 7,
    isSubscribable: true,
    tags: ["new"],
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/29_nandini_goodlife_6041375cea.png",
  },
  {
    name: "Nandini Good Life Full Cream",
    category: "NANDINI GOOD LIFE MILK",
    unit: "500 ml",
    shopPrice: 32,
    sellingPrice: 38,
    description: "Premium full cream Good Life milk",
    storageTemp: "2-8°C",
    shelfLife: 7,
    isSubscribable: true,
    rating: 4.8,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/29_nandini_goodlife_6041375cea.png",
  },

  // ─── FLAVORED MILK IN PET BOTTLES ──────────────────────────────────
  {
    name: "Nandini Badam Milk PET Bottle",
    category: "FLAVORED MILK IN PET BOTTLES",
    unit: "200 ml",
    shopPrice: 28,
    sellingPrice: 35,
    description: "Badam milk in convenient PET bottle",
    storageTemp: "2-8°C",
    shelfLife: 14,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/9_pet_bottles_01c4646396.png",
  },
  {
    name: "Nandini Chocolate Milk PET Bottle",
    category: "FLAVORED MILK IN PET BOTTLES",
    unit: "200 ml",
    shopPrice: 28,
    sellingPrice: 35,
    description: "Chocolate milk in PET bottle",
    storageTemp: "2-8°C",
    shelfLife: 14,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/9_pet_bottles_01c4646396.png",
  },
  {
    name: "Nandini Strawberry Milk PET Bottle",
    category: "FLAVORED MILK IN PET BOTTLES",
    unit: "200 ml",
    shopPrice: 28,
    sellingPrice: 35,
    description: "Strawberry flavored milk PET bottle",
    storageTemp: "2-8°C",
    shelfLife: 14,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/9_pet_bottles_01c4646396.png",
  },

  // ─── BUTTER MILK AND LASSI ─────────────────────────────────────────
  {
    name: "Nandini Buttermilk",
    category: "BUTTER MILK AND LASSI",
    unit: "200 ml",
    shopPrice: 12,
    sellingPrice: 15,
    description: "Refreshing spiced buttermilk",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    tags: ["bestseller"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/31_buttermillk_4384ca9033.png",
  },
  {
    name: "Nandini Sweet Lassi",
    category: "BUTTER MILK AND LASSI",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Thick creamy sweet lassi",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    rating: 4.7,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/31_buttermillk_4384ca9033.png",
  },
  {
    name: "Nandini Mango Lassi",
    category: "BUTTER MILK AND LASSI",
    unit: "200 ml",
    shopPrice: 22,
    sellingPrice: 28,
    description: "Mango flavored thick lassi",
    storageTemp: "2-8°C",
    shelfLife: 5,
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/31_buttermillk_4384ca9033.png",
  },
  {
    name: "Nandini Masala Buttermilk",
    category: "BUTTER MILK AND LASSI",
    unit: "500 ml",
    shopPrice: 22,
    sellingPrice: 28,
    description: "Spiced masala chaas, large pack",
    storageTemp: "2-8°C",
    shelfLife: 5,
    isSubscribable: true,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/31_buttermillk_4384ca9033.png",
  },

  // ─── SODA DRINKS JUICE ─────────────────────────────────────────────
  {
    name: "Nandini Mango Juice",
    category: "SODA DRINKS JUICE",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Real mango fruit juice",
    storageTemp: "Room temp",
    shelfLife: 90,
    tags: ["bestseller"],
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/32_Soda_0cfe455713.png",
  },
  {
    name: "Nandini Orange Juice",
    category: "SODA DRINKS JUICE",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Fresh orange fruit juice",
    storageTemp: "Room temp",
    shelfLife: 90,
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/32_Soda_0cfe455713.png",
  },
  {
    name: "Nandini Lychee Soda",
    category: "SODA DRINKS JUICE",
    unit: "200 ml",
    shopPrice: 18,
    sellingPrice: 22,
    description: "Refreshing lychee soda drink",
    storageTemp: "Room temp",
    shelfLife: 90,
    tags: ["new"],
    rating: 4.4,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/32_Soda_0cfe455713.png",
  },

  // ─── NANDINI PANNER NIPPATTU ───────────────────────────────────────
  {
    name: "Nandini Paneer Nippattu",
    category: "NANDINI PANNER NIPPATTU",
    unit: "200 g",
    shopPrice: 55,
    sellingPrice: 65,
    description: "Crispy Karnataka-style paneer nippattu",
    storageTemp: "Room temp",
    shelfLife: 60,
    tags: ["new"],
    rating: 4.6,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/PANEER_NIPPATTU_bcb638657b.jpg",
  },
  {
    name: "Nandini Butter Nippattu",
    category: "NANDINI PANNER NIPPATTU",
    unit: "200 g",
    shopPrice: 50,
    sellingPrice: 60,
    description: "Butter flavored traditional nippattu",
    storageTemp: "Room temp",
    shelfLife: 60,
    rating: 4.5,
    image: "https://kmf-website.s3.ap-south-1.amazonaws.com/PANEER_NIPPATTU_bcb638657b.jpg",
  },
]

// Enrich all products
const enriched = products.map((p) => ({
  ...p,
  isVeg: p.isVeg ?? true,
  inStock: true,
  marginPercent: Math.round(((p.sellingPrice - p.shopPrice) / p.shopPrice) * 100),
}))

// ── Main ─────────────────────────────────────────────────────────────
async function main() {
  console.log("Connecting to MongoDB...")
  await mongoose.connect(MONGO_URI)
  console.log("Connected!\n")

  const deleteResult = await Product.deleteMany({})
  console.log(`Deleted ${deleteResult.deletedCount} old products.`)

  const inserted = await Product.insertMany(enriched)
  console.log(`Inserted ${inserted.length} Nandini KMF products.\n`)

  const cats = [...new Set(enriched.map((p) => p.category))]
  console.log(`Categories (${cats.length}):`)
  for (const cat of cats) {
    const count = enriched.filter((p) => p.category === cat).length
    console.log(`  ${cat}: ${count} products`)
  }

  console.log("\nDone! All products seeded with real KMF images.")
  await mongoose.disconnect()
  process.exit(0)
}

main().catch((err) => {
  console.error("Seed failed:", err)
  process.exit(1)
})
